In [147]:
import numpy as np
import random 

np.random.seed(1)
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)

print("a")
print(a)
print("b")
print(b)

c = a + b

print("output")
print(c)

a
[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
b
[[ 1.74481176]
 [-0.7612069 ]]
output
[[ 3.36915713  1.13305535  1.21664001]
 [-1.83417552  0.10420073 -3.0627456 ]]
